"""
seed_baseline.py — Extract current parameter values and generate baseline.py.

Reads exact constants from config.py and fo_strategies.py using inspect.signature()
for constructor defaults. Run once to initialise autoresearch/baseline.py.

Usage:
    cd ~/financial-agent-india && python3 autoresearch/seed_baseline.py
"""

import inspect
import os
import sys
import textwrap

# Ensure the project root is on the path so config / fo_strategies import cleanly.
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

import config as cfg
import fo_strategies as strat


def _sig_default(cls, param: str):
    """Return the default value for a constructor parameter."""
    sig = inspect.signature(cls.__init__)
    p = sig.parameters.get(param)
    if p is None or p.default is inspect.Parameter.empty:
        raise KeyError(f"{cls.__name__}.__init__ has no param '{param}'")
    return p.default


def build_config() -> dict:
    """Assemble baseline config from live source constants."""
    return {
        # ── Signal parameters (Tier 1) ──────────────────────────────────────
        "rsi_period": 14,
        "atr_period": 14,
        "supertrend_period": cfg.SUPERTREND_PERIOD,
        "supertrend_multiplier": cfg.SUPERTREND_MULTIPLIER,
        "volume_lookback": 20,
        "adx_threshold": 20,
        "signal_weights": {"buildup": 2.0, "oi": 1.5, "price": 1.0},
        "rsi_overbought_penalty": 70,
        "rsi_oversold_penalty": 30,
        "volume_bonus_threshold": 1.5,

        # ── Entry / exit logic (Tier 2) ─────────────────────────────────────
        "futures_score_threshold": _sig_default(strat.FuturesStrategy, "score_threshold"),
        "futures_target_atr_mult": _sig_default(strat.FuturesStrategy, "target_atr_mult"),
        "futures_sl_atr_mult": _sig_default(strat.FuturesStrategy, "sl_atr_mult"),
        "condor_min_vix": cfg.CONDOR_MIN_VIX,
        "condor_max_vix": cfg.CONDOR_MAX_VIX,
        "condor_target_pct": cfg.CONDOR_TARGET_PCT,
        "condor_sl_multiplier": cfg.CONDOR_SL_MULTIPLIER,
        "spread_profit_cap_pct": cfg.SPREAD_PROFIT_CAP_PCT,
        "spread_sl_multiplier": cfg.CREDIT_SPREAD_SL_MULTIPLIER,
        "trailing_activation_pct": cfg.TRAILING_SL_ACTIVATION_PCT,
        "trailing_atr_mult": cfg.TRAILING_SL_ATR_MULT,
        "max_hold_days": _sig_default(strat.FuturesStrategy, "max_hold_days"),
        "momentum_score_threshold": _sig_default(strat.MomentumStrategy, "score_threshold"),
        "momentum_sl_pct": _sig_default(strat.MomentumStrategy, "sl_pct"),
        "momentum_target_pct": _sig_default(strat.MomentumStrategy, "target_pct"),
        "momentum_time_exit_days": _sig_default(strat.MomentumStrategy, "time_exit_days"),

        # ── Regime & allocation (Tier 3) ────────────────────────────────────
        "cash_trigger_vix": cfg.CASH_TRIGGER_VIX,
        # Stored as bare percentage (8.0) → normalise to decimal for model consumption
        "cash_trigger_monthly_dd": cfg.CASH_TRIGGER_MONTHLY_DRAWDOWN_PCT / 100.0,
        "cash_trigger_consecutive_losses": cfg.CASH_TRIGGER_CONSECUTIVE_LOSSES,
        "alloc_spreads_max": cfg.ALLOC_SPREADS_MAX,
        "alloc_condor_max": cfg.ALLOC_IRON_CONDOR_MAX,
        "alloc_momentum_max": cfg.ALLOC_MOMENTUM_MAX,
        "cash_min": cfg.CASH_RESERVE_PCT,

        # ── Custom logic hooks (Tier 4) ─────────────────────────────────────
        # None means use built-in defaults; autoresearch may swap in lambdas.
        "custom_signal_fn": None,
        "custom_entry_filter_fn": None,
        "custom_exit_fn": None,
    }


def _repr_value(v) -> str:
    """Format a value for code generation, preserving dict/None types."""
    if v is None:
        return "None"
    if isinstance(v, dict):
        inner = ", ".join(f'"{k}": {_repr_value(val)}' for k, val in v.items())
        return "{" + inner + "}"
    if isinstance(v, float):
        return repr(v)
    if isinstance(v, str):
        return repr(v)
    return repr(v)


def generate_baseline_source(cfg_dict: dict) -> str:
    """Render baseline.py source from the config dict."""
    lines = [
        '"""',
        "baseline.py — Autoresearch baseline configuration.",
        "",
        "AUTO-GENERATED by autoresearch/seed_baseline.py.",
        "Do NOT edit by hand; re-run seed_baseline.py to refresh from source.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "",
        "def get_strategy_config() -> dict:",
        '    """Return the full baseline parameter dict."""',
        "    return {",
    ]

    section_comments = {
        "rsi_period": "# Signal parameters (Tier 1)",
        "futures_score_threshold": "# Entry / exit logic (Tier 2)",
        "cash_trigger_vix": "# Regime & allocation (Tier 3)",
        "custom_signal_fn": "# Custom logic hooks (Tier 4) — None = use built-in defaults",
    }

    for key, val in cfg_dict.items():
        if key in section_comments:
            lines.append(f"        {section_comments[key]}")
        lines.append(f"        {repr(key)}: {_repr_value(val)},")

    lines.append("    }")
    lines.append("")
    return "\n".join(lines)


def main():
    cfg_dict = build_config()
    src = generate_baseline_source(cfg_dict)

    out_path = os.path.join(ROOT, "autoresearch", "baseline.py")
    with open(out_path, "w") as fh:
        fh.write(src)

    print(f"Written: {out_path}")
    print(f"Keys:    {len(cfg_dict)}")

    # Quick sanity: re-import and spot-check a few values
    import importlib.util
    spec = importlib.util.spec_from_file_location("baseline", out_path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    loaded = mod.get_strategy_config()
    assert loaded["futures_score_threshold"] == strat.ENTRY_SCORE_THRESHOLD, "score_threshold mismatch"
    assert loaded["condor_min_vix"] == cfg.CONDOR_MIN_VIX, "condor_min_vix mismatch"
    print("Sanity checks passed.")


if __name__ == "__main__":
    main()
